# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-08-16 16:49
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0001_initial'),
        ('operation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserErrorChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_answer', models.SmallIntegerField(choices=[(1, 'A'), (2, 'B'), (3, 'C'), (4, 'D')], default=0, verbose_name='用户的错误答案')),
                ('error_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='做题时间')),
                ('status', models.SmallIntegerField(choices=[(1, '未修改'), (2, '已修改')], default=0, verbose_name='错误题状态')),
                ('choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.ChoiceQuestion', verbose_name='做错的选择题')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name_plural': '用户错误选择题',
                'verbose_name': '用户错误选择题',
            },
        ),
        migrations.CreateModel(
            name='UserPass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.SmallIntegerField(choices=[(1, '未开通'), (2, '已开通'), (3, '已完成')], default=0, verbose_name='关卡状态')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Lesson', verbose_name='关卡')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name_plural': '用户关卡信息',
                'verbose_name': '用户关卡信息',
            },
        ),
    ]
