# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-08-17 09:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0002_usererrorchoice_userpass'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercourse',
            name='status',
            field=models.SmallIntegerField(choices=[(1, '未学习'), (2, '学习中'), (3, '已学习')], default=0, verbose_name='课程状态'),
        ),
    ]
