# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-08-31 16:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0006_userfavarticle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userfavarticle',
            name='article',
        ),
        migrations.AddField(
            model_name='userfavarticle',
            name='article_id',
            field=models.IntegerField(default=0, verbose_name='文章id'),
        ),
    ]
