# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-09-05 16:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0007_auto_20180831_1621'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercourse',
            name='status',
        ),
        migrations.AddField(
            model_name='usercourse',
            name='course_status',
            field=models.SmallIntegerField(choices=[(1, '未开通'), (2, '已开通')], default=1, verbose_name='课程状态'),
        ),
        migrations.AddField(
            model_name='usercourse',
            name='study_status',
            field=models.SmallIntegerField(choices=[(1, '未学习'), (2, '学习中'), (3, '已学习')], default=1, verbose_name='课程的学习状态'),
        ),
        migrations.AddField(
            model_name='userpass',
            name='choice_status',
            field=models.SmallIntegerField(default=0, verbose_name='关卡选择题库答题状态'),
        ),
    ]
