# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-08-16 09:14
from __future__ import unicode_literals

import DjangoUeditor.models
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChoiceBank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='题库名称')),
                ('desc', models.CharField(blank=True, max_length=200, null=True, verbose_name='题库描述')),
                ('click_nums', models.IntegerField(default=0, verbose_name='点击数')),
                ('complete_times', models.IntegerField(default=0, verbose_name='建议完成时长(分钟数)')),
                ('is_complete', models.BooleanField(default=False, verbose_name='是否完成')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '选择题库',
                'verbose_name_plural': '选择题库',
            },
        ),
        migrations.CreateModel(
            name='ChoiceQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_num', models.IntegerField(verbose_name='题目编号')),
                ('question_content', models.CharField(max_length=500, verbose_name='题目内容')),
                ('choiceA', models.CharField(max_length=200, verbose_name='选项A')),
                ('choiceB', models.CharField(max_length=200, verbose_name='选项B')),
                ('choiceC', models.CharField(max_length=200, verbose_name='选项C')),
                ('choiceD', models.CharField(max_length=200, verbose_name='选项D')),
                ('answer', models.SmallIntegerField(choices=[(1, 'A'), (2, 'B'), (3, 'C'), (4, 'D')], default=0, verbose_name='答案')),
                ('explain', models.TextField(verbose_name='答案解释')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('choicebank', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='courses.ChoiceBank', verbose_name='选择题库')),
            ],
            options={
                'verbose_name': '选择题',
                'verbose_name_plural': '选择题',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='课程名')),
                ('desc', models.CharField(max_length=300, verbose_name='课程描述')),
                ('detail', DjangoUeditor.models.UEditorField(default='', verbose_name='课程详情')),
                ('degree', models.CharField(choices=[('cj', '初级'), ('zj', '中级'), ('gj', '高级')], max_length=2, verbose_name='难度')),
                ('learn_times', models.IntegerField(default=0, verbose_name='建议学习时长')),
                ('students', models.IntegerField(default=0, verbose_name='学习人数')),
                ('fav_nums', models.IntegerField(default=0, verbose_name='收藏人数')),
                ('image', models.ImageField(upload_to='courses/%Y/%m', verbose_name='课程封面')),
                ('click_nums', models.IntegerField(default=0, verbose_name='点击数')),
                ('direction', models.CharField(choices=[('base', '基础课程'), ('project', '项目课程')], default='base', max_length=10, verbose_name='课程方向')),
                ('tag', models.CharField(default='', max_length=10, verbose_name='课程标签')),
                ('youneed_know', models.CharField(default='', max_length=300, verbose_name='课程须知')),
                ('teacher_tell', models.CharField(default='', max_length=300, verbose_name='老师告诉你')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '课程',
                'verbose_name_plural': '课程',
            },
        ),
        migrations.CreateModel(
            name='CourseCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=36, verbose_name='课程分类')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '课程分类',
                'verbose_name_plural': '课程分类',
            },
        ),
        migrations.CreateModel(
            name='CourseDirection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(max_length=36, verbose_name='课程方向')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '课程方向',
                'verbose_name_plural': '课程方向',
            },
        ),
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500, verbose_name='问题')),
                ('answer', models.CharField(max_length=1500, verbose_name='回答')),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQ',
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='关卡名')),
                ('image', models.ImageField(default='', max_length=128, upload_to='', verbose_name='关卡图')),
                ('learn_times', models.IntegerField(default=0, verbose_name='建议完成时长')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('learn_require', models.CharField(max_length=300, verbose_name='关卡学习要求')),
                ('learn_target', models.CharField(max_length=300, verbose_name='关卡学习目标')),
                ('resource', models.CharField(max_length=300, verbose_name='关卡学习资源网盘地址')),
                ('tutorial', models.CharField(default='', max_length=200, verbose_name='关卡教程地址')),
                ('opt_require', models.CharField(max_length=300, verbose_name='关卡实操要求')),
                ('ext_resource', models.CharField(max_length=300, verbose_name='关卡扩展资源网盘地址')),
                ('choice_detail', models.CharField(default='', max_length=100, verbose_name='选择题描述')),
                ('program_detail', models.CharField(default='', max_length=100, verbose_name='编程题描述')),
                ('open_level', models.BooleanField(default=False, verbose_name='开通关卡')),
                ('pass_level', models.BooleanField(default=False, verbose_name='通过关卡')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Course', verbose_name='课程')),
            ],
            options={
                'verbose_name': '课程关卡',
                'verbose_name_plural': '课程关卡',
            },
        ),
        migrations.CreateModel(
            name='ProgramBank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='题库名称')),
                ('desc', models.CharField(blank=True, max_length=200, null=True, verbose_name='题库描述')),
                ('click_nums', models.IntegerField(default=0, verbose_name='点击数')),
                ('complete_times', models.IntegerField(default=0, verbose_name='建议完成时长(分钟数)')),
                ('is_complete', models.BooleanField(default=False, verbose_name='是否完成')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('lesson', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='courses.Lesson', verbose_name='课程关卡')),
            ],
            options={
                'verbose_name': '实操题库',
                'verbose_name_plural': '实操题库',
            },
        ),
        migrations.CreateModel(
            name='ProgramQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_num', models.IntegerField(verbose_name='题目编号')),
                ('question_title', models.CharField(default='', max_length=36, verbose_name='编程题目')),
                ('question_content', models.TextField(verbose_name='题目内容')),
                ('download', models.FileField(default='', upload_to='program/download/%Y/%m', verbose_name='源码文件')),
                ('url', models.CharField(default='', max_length=200, verbose_name='题目讲解视频地址')),
                ('essentials', models.CharField(max_length=500, verbose_name='解题思路')),
                ('image', models.ImageField(blank=True, null=True, upload_to='program/image/%Y/%m', verbose_name='运行结果截图')),
                ('is_comment', models.BooleanField(default=False, verbose_name='是否提供点评')),
                ('is_complete', models.BooleanField(default=False, verbose_name='是否完成')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('lesson', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='courses.Lesson', verbose_name='课程关卡')),
                ('program_bank', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='courses.ProgramBank', verbose_name='实操题库')),
            ],
            options={
                'verbose_name': '编程题',
                'verbose_name_plural': '编程题',
            },
        ),
        migrations.CreateModel(
            name='ProgramResultImg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='', verbose_name='运行截图')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '项目运行截图',
                'verbose_name_plural': '项目运行截图',
            },
        ),
        migrations.CreateModel(
            name='ProgramUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload', models.FileField(blank=True, default='', null=True, upload_to='program/upload/file/%Y/%m', verbose_name='源码文件')),
                ('image', models.ImageField(blank=True, null=True, upload_to='program/upload/image/%Y/%m', verbose_name='运行结果截图')),
                ('grade', models.CharField(blank=True, choices=[('优秀', 'A+'), ('优良', 'A'), ('良好', 'B'), ('及格', 'C'), ('不及格', 'D')], max_length=5, null=True, verbose_name='等级')),
                ('learned', models.TextField(blank=True, default='', null=True, verbose_name='练习心得')),
                ('comment', models.TextField(blank=True, default='', null=True, verbose_name='项目点评')),
                ('is_complete', models.BooleanField(default=False, verbose_name='是否完成')),
                ('is_show', models.BooleanField(default=False, verbose_name='是否展示')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('lesson', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='courses.Lesson', verbose_name='关卡')),
                ('programquestion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.ProgramQuestion', verbose_name='编程题')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '编程题结果',
                'verbose_name_plural': '编程题结果',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='视频名')),
                ('learn_times', models.IntegerField(default=0, verbose_name='视频时长(分钟数)')),
                ('url', models.CharField(default='', max_length=200, verbose_name='访问地址')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Lesson', verbose_name='课程关卡')),
            ],
            options={
                'verbose_name': '视频',
                'verbose_name_plural': '视频',
            },
        ),
        migrations.AddField(
            model_name='programresultimg',
            name='programupload',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.ProgramUpload', verbose_name='编程题结果'),
        ),
        migrations.AddField(
            model_name='faq',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Lesson', verbose_name='课程关卡'),
        ),
        migrations.AddField(
            model_name='course',
            name='coursecategory',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='courses.CourseCategory', verbose_name='课程分类'),
        ),
        migrations.AddField(
            model_name='choicequestion',
            name='lesson',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='courses.Lesson', verbose_name='课程关卡'),
        ),
        migrations.AddField(
            model_name='choicebank',
            name='lesson',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='courses.Lesson', verbose_name='课程关卡'),
        ),
    ]
