# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-08-17 10:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='open_level',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='pass_level',
        ),
    ]
