# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-08-21 13:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20180817_1014'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='choice_detail',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='program_detail',
        ),
    ]
