# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-09-06 15:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20180821_1328'),
    ]

    operations = [
        migrations.AddField(
            model_name='programquestion',
            name='program_type',
            field=models.SmallIntegerField(choices=[(1, '课堂练习'), (2, '课后扩展')], default=1, verbose_name='编程题类型'),
        ),
    ]
