# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-06-11 14:51
from __future__ import unicode_literals

import DjangoUeditor.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LivePreview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=36, verbose_name='标题')),
                ('content', DjangoUeditor.models.UEditorField(default='', verbose_name='直播内容')),
                ('live_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='直播时间')),
                ('link', models.URLField(max_length=128, verbose_name='直播链接')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '直播预告',
                'verbose_name_plural': '直播预告',
            },
        ),
    ]
