# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-08-16 09:14
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectShow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=36, verbose_name='项目名称')),
                ('degree', models.CharField(choices=[('cj', '初级'), ('zj', '中级'), ('gj', '高级')], default='', max_length=2, verbose_name='难度')),
                ('image', models.ImageField(max_length=128, upload_to='project/show/images/%Y/%m', verbose_name='项目图片')),
                ('describe', models.CharField(max_length=128, verbose_name='项目描述')),
                ('url', models.URLField(verbose_name='项目讲解链接')),
                ('code', models.FileField(max_length=128, upload_to='project/show/files/%Y/%m', verbose_name='项目源码')),
                ('click_num', models.IntegerField(default=0, verbose_name='点击数')),
                ('students', models.IntegerField(default=0, verbose_name='学习人数')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('course', models.ManyToManyField(default='', to='courses.Course', verbose_name='相关课程')),
                ('coursecategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.CourseCategory', verbose_name='分类')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='作者')),
            ],
            options={
                'verbose_name': '项目展示',
                'verbose_name_plural': '项目展示',
            },
        ),
    ]
