# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-09-12 11:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_auto_20180911_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectshow',
            name='integral',
            field=models.IntegerField(default=0, verbose_name='参与项目所需积分'),
        ),
        migrations.AlterField(
            model_name='projectshow',
            name='plan_file',
            field=models.FileField(blank=True, default='', max_length=128, null=True, upload_to='project/show/files/%Y/%m', verbose_name='项目计划文档'),
        ),
        migrations.AlterField(
            model_name='projectshow',
            name='require_file',
            field=models.FileField(blank=True, default='', max_length=128, null=True, upload_to='project/show/files/%Y/%m', verbose_name='项目需求文档'),
        ),
        migrations.AlterField(
            model_name='projectshow',
            name='test_file',
            field=models.FileField(blank=True, default='', max_length=128, null=True, upload_to='project/show/files/%Y/%m', verbose_name='项目测试说明'),
        ),
    ]
