# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-09-19 08:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_projectshow_resouce'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectshow',
            name='tag',
            field=models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='项目标签'),
        ),
    ]
