# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-08-31 16:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='fav_num',
            field=models.IntegerField(default=0, verbose_name='收藏次数'),
        ),
    ]
